### ISSUE TITLE
Resend Breaks Email

### ISSUE THREAD

**Issue by slyvioborin** [awesomemotive/wp-mail-logging#166] opened 2023-05-11 00:35 UTC
If you resend the email by using the button on the Email Log page, it breaks the email sent. While the first email sent is normal, resent email is raw HTML.

**Comment by donmhico** [comment] 2023-05-11 04:49
@slyvioborin - Thank you for creating this issue. Can you provide more information? Like what PHP version and WordPress version were you using? I tried reproducing with the emails sent by WooCommerce and WPForms plugins and unfortunately I can't reproduce the issue.

It will be awesome if you can provide your steps to reproduce the issue.

**Comment by slyvioborin** [comment] 2023-05-11 23:53
PHP version: 8.0.28
Wordpress version: 6.2
Language: tr_TR
WP Mail Logging Version: 1.11.0
WP Mail SMTP Version: 3.8.0

Reproduction steps:
Send test email from "Email Test" page in WP Mail SMTP plugin
test email sent normally (everything good)
view the mail sent from "Email Log" page in WP Mail Logging page.
use resend button (sends the previous email as plain text (all html codes as plain text))

**Comment by donmhico** [comment] 2023-05-25 12:30
@slyvioborin - Thank you for your response and for providing the steps to reproduce. We're able to replicate the issue.

The issue is not with WP Mail Logging. How WP Mail Logging works is that it captures the mail sent via [wp_mail filter](https://github.com/awesomemotive/wp-mail-logging/blob/master/src/WPML_Plugin.php#L392). Then it re-uses the captured headers when re-sending the email (see [here](https://github.com/awesomemotive/wp-mail-logging/blob/master/src/WPML_Email_Resender.php#L34-L48)).

In the case of WP Mail SMTP, the email test doesn't explicitly add the `Content-Type: text/html` in the headers and just uses [wp_mail_content_type](https://developer.wordpress.org/reference/hooks/wp_mail_content_type/) filter to set the content type. The email is still sent as HTML because when this filter is activated, the `$phpmailer` object's content type is set to HTML but the `Content-Type: text/html` is not added in the headers.

So when `wp_mail` hook from WP Mail Logging captures the test email from WP Mail SMTP, it does not have the `Content-Type: text/html` header. So when we resend it, it does not know that the test email is an HTML.

The good news is this issue should only affect emails that was sent without `Content-Type: text/html` header. If you test this with WooCommerce, the resend will work as intended.

We also are fixing this issue on WP Mail SMTP's side.

**Comment by donmhico** [comment] 2024-10-07 12:40
Just to give an update, we fix this issue with https://github.com/awesomemotive/wp-mail-logging/commit/758fec075641bff1baa334c75ec596ca91c9b6f2. Basically, we will now use the filter [wp_mail_content_type](https://developer.wordpress.org/reference/hooks/wp_mail_content_type/) to determine what is the `Content-Type` to use on resend.

This will be included in our next release.

**Closed by donmhico** 2024-10-07 12:40 UTC
