### ISSUE TITLE
WP mail log is not resending emails

### ISSUE THREAD

**Issue by helprequired** [awesomemotive/wp-mail-logging#80] opened 2018-09-13 18:45 UTC
WP mail log is not sending emails to my email account like it usually does. What could be wrong?

**Comment by No3x** [comment] 2018-09-13 18:49
The plugin doesn't send mails unless you resend mails. What do you mean?

**Comment by helprequired** [comment] 2018-09-13 18:57
Yes that is what i mean. When i resend the emails form the WP Log it
doesn't sen it to my account

**Comment by No3x** [comment] 2018-09-13 18:58
But the mail you send is logged?

**Comment by helprequired** [comment] 2018-09-13 19:00
Exactly. I see the mail in the log. I resend it and it reappears at the top
of the log right after i resend it but it doesn't appear in my gmail's inbox

**Comment by No3x** [comment] 2018-09-13 19:04
Please check the php error log if there are any hints.

**Comment by Morgunov-Vitaly** [comment] 2018-10-17 18:19
I have a very similar issue. In some cases, I can see massage in the WP Mail Logging log, but it doesn't send to my mailbox. How can I fix it?

**Comment by kernest** [comment] 2018-10-18 06:53
Hey,

I have similar issue with resend some mail.

The original mail is sent correctly.
Resend is not working. No errors in logs etc.

Some mails are possible to resend, but those mails with HTML is not resending.

**Comment by No3x** [comment] 2018-10-23 17:19
Then there is something special about the mail. Please provide a mail to reproduce.

**Comment by kernest** [comment] 2018-11-01 20:53
Sorry for slow reply.

I have attach an example.

`Time:
1. november 2018 14:56
Receiver:
testing@test.com
Subject:
Test - 43 - KE
Message:
<title></title>  <table width="100%" cellpadding="0" cellspacing="0" bgcolor="#ffffff"> <tr> <td> <table width="1000" border="0" cellspacing="0" align="center"> <tr> <td> <table align="center" width="100%" bgcolor="#ffffff" cellpadding="0" cellspacing="0" style="font-size:12px;color:black;font-family:Arial, sans-serif;font-weight:bold"> <tr> <td> Navn: Test </td> <td> Antal uger: 2 uger </td> <td> Første uge: 43 </td> <td> Stilling: Test </td> <td> Kopi til: </td> </tr> </table> </td> </tr> <table align="center" width="1000" cellpadding="1" cellspacing="0" style="font-size:11px;color:black;font-family:Arial, sans-serif;text-align:center"><br /> <tr bgcolor="#eeeeee" style="font-weight:bold"> <td width="30">Sag</td> <td style="border-left:1px solid #000000;padding:5px">Plads</td> <td width="20" style="border-left:1px solid #000000;padding:5px">KM t.o.f. plads</td> <td width="20" style="border-left:1px solid #000000;padding:5px">KM i arbejdstid</td> <td width="20" style="border-left:1px solid #000000;padding:5px">Parkering</td> <td width="20" style="border-left:1px solid #000000;padding:5px">Man</td> <td width="20" style="border-left:1px solid #000000;padding:5px">Tirs</td> <td width="20" style="border-left:1px solid #000000;padding:5px">Ons</td> <td width="20" style="border-left:1px solid #000000;padding:5px">Tors</td> <td width="20" style="border-left:1px solid #000000;padding:5px">Fre</td> <td width="20" style="border-left:1px solid #000000;padding:5px">Lør</td> <td width="20" style="border-left:1px solid #000000;padding:5px">Søn</td> <td width="20" style="border-left:1px solid #000000;padding:5px">Sats</td> <td style="border-left:1px solid #000000;padding:5px">Samlet timer</td> <td style="border-left:1px solid #000000;padding:5px">Beløb</td> <td style="border-left:1px solid #000000;padding:5px">Samlet beløb</td> </tr> <tr> <td>Test</td> <td style="border-left:1px solid #000000">Test 1</td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000">7,5</td> <td style="border-left:1px solid #000000">7,5</td> <td style="border-left:1px solid #000000">7,5</td> <td style="border-left:1px solid #000000">7,5</td> <td style="border-left:1px solid #000000">7</td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000">37</td> <td style="border-left:1px solid #000000">0</td> <td style="border-left:1px solid #000000">0,00</td> </tr> <tr bgcolor="#eeeeee"> <td>0</td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000">7,5</td> <td style="border-left:1px solid #000000">7,5</td> <td style="border-left:1px solid #000000">7,5</td> <td style="border-left:1px solid #000000">7,5</td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000">30</td> <td style="border-left:1px solid #000000">0</td> <td style="border-left:1px solid #000000">0,00</td> </tr> <tr> <td>FF</td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000">7</td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000">7</td> <td style="border-left:1px solid #000000">0</td> <td style="border-left:1px solid #000000">0,00</td> </tr> <tr bgcolor="#eeeeee"> <td>0</td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000">0</td> <td style="border-left:1px solid #000000">0</td> <td style="border-left:1px solid #000000">0,00</td> </tr> <tr> <td></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> </tr> <tr bgcolor="#eeeeee"> <td></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> </tr> <tr> <td></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> </tr> <tr bgcolor="#eeeeee"> <td></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> <td style="border-left:1px solid #000000"></td> </tr> </table> <tr> <td> <br /><br /><br /> <table width="600" border="1" cellspacing="0" cellpadding="5" align="center" bgcolor="#ffffff" style="font-size:12px;color:black;font-family:Arial, sans-serif;text-align:center"> <caption style="font-weight:bold;font-size:16px;padding:5px">Total timer overblik</caption> <tr bgcolor="#eeeeee" style="font-weight:bold"> <td>Man</td> <td>Tirs</td> <td>Ons</td> <td>Tors</td> <td>Fre</td> <td>Lør</td> <td>Søn</td> <td>Total timer</td> </tr> <tr> <td>15</td> <td>15</td> <td>15</td> <td>15</td> <td>14</td> <td>0</td> <td>0</td> <td>74</td> </tr> </table> <br /> <table width="600" border="1" cellspacing="0" cellpadding="5" align="center" bgcolor="#ffffff" style="font-size:12px;color:black;font-family:Arial, sans-serif;text-align:center"> <caption style="font-weight:bold;font-size:16px;padding:5px">Total beløb overblik</caption> <tr bgcolor="#eeeeee" style="font-weight:bold"> <td>Total beløb</td> <td>Total samlet beløb</td> <td>Test</td> <td>Test</td> </tr> <tr> <td>0,00</td> <td>0,00</td> <td></td> <td>0,00</td> </tr> </table></td> </tr> </table></td></tr></table> 
Headers:
From: "test@test.com" Reply-To: Content-Type: text/html; charset=utf-8 X-Mailer: PHP/5.6.38
Attachments:
Error:`

**Comment by No3x** [comment] 2018-11-01 21:01
Thanks! I'm trying to reproduce it with that content. Did you modify something?

**Comment by kernest** [comment] 2018-11-01 21:18
Your welcome! 

Only changed some labels and the email addresses.

Nothing special - just for privacy 👍

**Comment by No3x** [comment] 2018-11-01 22:39
## Tests

Trying to send with header 
```
From: "test@test.com"
```
Doesnt work and results in a error:
```
Invalid address: (setFrom) "test@example.com"
```
So I tested with my usual data
```
From: admin@local.test
```
and
```
From: "admin" <admin@local.test>
```
### Current dev
The mail is logged and resend works too on my current development version of the plugin. The identical mail is logged.
### 1.8.5
In contrast 1.8.5 shows some strange behavior indeed. The headers are incorrectly mered into one without delimiter resulting in a 
```
Invalid address: (setFrom) admin@local.test Cc: admin2@local.test Reply-To: admin <admin@local.test
```
on the mail to resend.
But this is not your described behavior either, since you did not mention a error on the resend mail.
## Problem
Unfortunately it is really hard to reproduce. You can pass 3 different header formats to the wp_mail function namely:
- array
- string and their entries seperated by \n
- string and their entries seperated by \r\n

There are different types of email-address formats:
- user@example.com
- user@example.com, anotheruser@example.com
- User <user@example.com>
- User <user@example.com>, Another User <anotheruser@example.com>

There is a serialization and deserialization to the database that screws some cases.
I modified this process along various versions of the plugin so resend or even display might not work on old mails. So with each release it gets worse (combinatorial explosion).
I tried to clean this up a bit with the current dev version (currently and tested with [8bba0](https://github.com/No3x/wp-mail-logging/tree/8bba0b3f17cd75d500b71ffa8213e4f9b88e63f8)) and it seems to do well with this case and my tests during development.

## Summary
So I was not able to reproduce the issue but got something different. My advice is to wait for the next release and see if it helps (for new logged mails and even some old mails).

**Comment by kernest** [comment] 2018-11-02 22:21
Hi,

Thanks for your work!

Looking forward to next release and will check / test there!

**Comment by donmhico** [comment] 2023-05-11 10:53
@helprequired @kernest - Thank you for your input on this issue. I'm closing this issue for now. Unfortunately, we cannot reproduce the issue. Please test with our latest version and create a new issue if the issue still persists.

**Closed by donmhico** 2023-05-11 10:53 UTC
